version: '3.3'
services:
  server:
    build: server
    ports:
      - "5000:5000"
    restart: always
    environment:
      MYSQL_DATABASE: aktieninvestdb
      MYSQL_USER: aktieninvestuser
      MYSQL_PASSWORD: aktieninvestpass
      MYSQL_HOSTNAME: maria_db
    links:
      - maria_db
    depends_on:
      - maria_db
    # Host mount path overwrite for nodemon - only for DEV!
    volumes:
      # :Z may needs to be removed, if this does not work
      - ./server:/usr/src/app:Z
  jobs:
    build: jobs
    ports:
      - "8081:8081"
    restart: always
    environment:
      MYSQL_DATABASE: aktieninvestdb
      MYSQL_USER: aktieninvestuser
      MYSQL_PASSWORD: aktieninvestpass
      MYSQL_HOSTNAME: maria_db
    links:
      - maria_db
    depends_on:
      - maria_db
    volumes:
      - ./jobs:/usr/src/app:Z
  maria_db:
    # Use of a modified datbase in 'db'-folder.
    # See README.md for more information.
    build: db
    restart: always
    environment:
      MYSQL_DATABASE: aktieninvestdb
      MYSQL_USER: aktieninvestuser
      MYSQL_PASSWORD: aktieninvestpass
      MYSQL_RANDOM_ROOT_PASSWORD: aktieninvestpassroot
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8085:80
    environment:
      PMA_HOST: maria_db
  influxdb:
    container_name: influxdb
    image: influxdb
    restart: always
    ports:
      - "8086:8086/tcp"   # So we can access the WebUI
    environment:
      - TZ=Europe/Brussels
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
    ulimits:
      nofile:
        soft: 32768
        hard: 32768
  angular: # The name of the service
    container_name: angular  # Container name
    build: 
      context: angular
      dockerfile: Dockerfile
    ports: 
      - '80:80' # Port mapping
    volumes:
      - ./angular:/src/usr/app
  loadbolancer:
    build: ./nginx
    ports:
      - "8080:8080"
    depends_on:
      - server